/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/fCEQvEGlsMD
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"

export function card() {
  const products = [
    {
      id: 1,
      image: "/placeholder.svg",
      title: "Wireless Noise-Cancelling Headphones",
      description:
        "Experience immersive audio with our state-of-the-art noise-cancelling headphones. Enjoy your music, podcasts, and calls in peace.",
      price: 149.99,
    },
    {
      id: 2,
      image: "/placeholder.svg",
      title: "Ergonomic Desk Chair",
      description:
        "Upgrade your home office with our comfortable and supportive desk chair. Improve your posture and productivity.",
      price: 299.99,
    },
    {
      id: 3,
      image: "/placeholder.svg",
      title: "Smart Home Automation Kit",
      description:
        "Easily control your home's lighting, temperature, and security with our intuitive smart home automation kit.",
      price: 199.99,
    },
    {
      id: 4,
      image: "/placeholder.svg",
      title: "High-Performance Fitness Tracker",
      description:
        "Stay motivated and track your fitness goals with our advanced fitness tracker. Monitor your heart rate, steps, and more.",
      price: 99.99,
    },
  ]
  return (
    <section className="w-full py-12 md:py-24">
      <div className="container grid gap-6 md:gap-8 px-4 md:px-6">
        <div className="flex flex-col md:flex-row items-start md:items-center gap-4 md:gap-8">
          <h1 className="text-2xl font-bold tracking-tight">Featured Products</h1>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 lg:gap-6 xl:gap-8">
          {products.map((product) => (
            <div key={product.id} className="bg-background rounded-lg shadow-lg overflow-hidden">
              <img
                src="/placeholder.svg"
                alt={product.title}
                width={600}
                height={400}
                className="w-full h-48 object-cover"
              />
              <div className="p-6 space-y-4">
                <h3 className="text-xl font-semibold">{product.title}</h3>
                <p className="text-muted-foreground">{product.description}</p>
                <div className="flex items-center justify-between">
                  <span className="text-2xl font-bold">${product.price.toFixed(2)}</span>
                  <Button>Add to Cart</Button>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  )
}
